name: TEST

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  testing-on-push:
    runs-on: ubuntu-latest
    steps:
      - name: Testing
        run: echo "Pushing is working, and my variable is ${{ secrets.VARIABLE1 }}!"
